default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  host: localhost

development:
  <<: *default
  database: silver_guild_development

test:
  <<: *default
  database: silver_guild_test
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>

production:
  <<: *default
  database: silver_guild_production
  username: silver_guild  # You might want to use a different username in production
  password: <%= ENV['SILVER_GUILD_DATABASE_PASSWORD'] %>